[package]
name = "js_bridge"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
wasm-bindgen = "0.2.78"
serde_json = "1.0"
serde = "1.0"
js-sys = "0.3"
mytil = { path = "../../libs/mytil"}
names = { version = "0.12.0", default-features = false }